const goodsInfo618 =
  {
    tabsData:['手机','电脑','数码','家电','影音娱乐','个人护理','出行','办公','游戏','智能学习','全品类'],
    goodsData:[
      {
        category:'手机',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            },{
              price:100,
              condition:'满188元可用'
            }
          ],
          jd:[
            {
              price:200,
              condition:'满288元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:1157,
            name:'坚果3',
            originalPrize:1499,
            mibaoPrize:90,
            mibaoUnit:'/月',
            discontPrize:40,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shouji-1.png')
          },{
            id:1171,
            name:'OPPO R15',
            originalPrize:2999,
            mibaoPrize:207,
            mibaoUnit:'/月',
            discontPrize:107,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shouji-2.png')
          },{
            id:1130,
            name:'iPhone X',
            originalPrize:8388,
            mibaoPrize:396,
            mibaoUnit:'/月',
            discontPrize:196,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shouji-3.png')
          }
        ],
      },
      {
        category:'电脑',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            },{
              price:100,
              condition:'满188元可用'
            }
          ],
          jd:[
            {
              price:200,
              condition:'满288元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:1320,
            name:'AOC AG322FCX 31.5英寸曲面屏',
            originalPrize:2700,
            mibaoPrize:147,
            mibaoUnit:'/月',
            discontPrize:97,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/diannao-1.png')
          },{
            id:563,
            name:'Dell Vostro 15',
            originalPrize:3499,
            mibaoPrize:199,
            mibaoUnit:'/月',
            discontPrize:99,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/diannao-2.png')
          },{
            id:1188,
            name:'MacBook Air 2017',
            originalPrize:7000,
            mibaoPrize:297,
            mibaoUnit:'/月',
            discontPrize:97,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/diannao-3.png')
          }
        ],
      },
      {
        category:'数码',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            },{
              price:150,
              condition:'满288元可用'
            }
          ],
          jd:[
            {
              price:200,
              condition:'满488元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:790,
            name:'大疆DJI 晓Spark无人机',
            originalPrize:5000,
            mibaoPrize:180,
            mibaoUnit:'(3天)',
            discontPrize:130,
            discontUnit:'3天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shuma-1.png')
          },{
            id:534,
            name:'佳能M100 15-45旅游微单',
            originalPrize:3500,
            mibaoPrize:308,
            mibaoUnit:'(14天)',
            discontPrize:158,
            discontUnit:'14天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shuma-2.png')
          },{
            id:1315,
            name:'大疆御Mavic Air全能套装',
            originalPrize:6499,
            mibaoPrize:560,
            mibaoUnit:'(7天)',
            discontPrize:360,
            discontUnit:'7天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/shuma-3.png')
          }
        ],
      },
      {
        category:'家电',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            },{
              price:100,
              condition:'满188元可用'
            }
          ],
          jd:[
            {
              price:200,
              condition:'满388元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:72,
            name:'东芝电视机 1500系列',
            originalPrize:1499,
            mibaoPrize:89,
            mibaoUnit:'/月',
            discontPrize:39,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/jiadian-1.png')
          },{
            id:1265,
            name:'霍尼韦尔 即热净水器',
            originalPrize:3999,
            mibaoPrize:249,
            mibaoUnit:'/月',
            discontPrize:149,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/jiadian-2.png')
          },{
            id:397,
            name:'范罗士AM II空气净化器',
            originalPrize:9800,
            mibaoPrize:450,
            mibaoUnit:'/月',
            discontPrize:250,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/jiadian-3.png')
          }
        ],
      },
      {
        category:'影音娱乐',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            }
          ],
          jd:[
            {
              price:100,
              condition:'满188元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:1154,
            name:'Beats Pill+',
            originalPrize:1588,
            mibaoPrize:92,
            mibaoUnit:'/月',
            discontPrize:42,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/yingyinyule-1.png')
          },{
            id:636,
            name:'Beats Powerbeats3 Wireless',
            originalPrize:1488,
            mibaoPrize:99,
            mibaoUnit:'/月',
            discontPrize:49,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/yingyinyule-2.png')
          },{
            id:836,
            name:'森海塞尔MOMENTUM Wireless',
            originalPrize:2899,
            mibaoPrize:209,
            mibaoUnit:'/月',
            discontPrize:109,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/yingyinyule-3.png')
          }
        ],
      },
      {
        category:'个人护理',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            },{
              price:100,
              condition:'满188元可用'
            }
          ],
          jd:[
            {
              price:200,
              condition:'满388元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:925,
            name:'TouchBeauty声波美容仪',
            originalPrize:1680,
            mibaoPrize:109,
            mibaoUnit:'/月',
            discontPrize:59,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/gerenhuli-1.png')
          },{
            id:1325,
            name:'戴森 HD01 吹风机',
            originalPrize:2990,
            mibaoPrize:210,
            mibaoUnit:'/月',
            discontPrize:110,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/gerenhuli-2.png')
          },{
            id:943,
            name:'Tripollar Stop美颜仪',
            originalPrize:3588,
            mibaoPrize:492,
            mibaoUnit:'/月',
            discontPrize:292,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/gerenhuli-3.png')
          }
        ],
      },
      {
        category:'出行',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            }
          ],
          jd:[
            {
              price:100,
              condition:'满388元可用'
            }
          ]
        },
        goodsInfoList:[
          {
            id:939,
            name:'Britax百代新生儿安全座椅',
            originalPrize:2000,
            mibaoPrize:88,
            mibaoUnit:'(3天)',
            discontPrize:38,
            discontUnit:'3天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/chuxing-1.png')
          },{
            id:932,
            name:'米家电动滑板车',
            originalPrize:1999,
            mibaoPrize:159,
            mibaoUnit:'/月',
            discontPrize:109,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/chuxing-2.png')
          },{
            id:950,
            name:'小米9号体感智能平衡车',
            originalPrize:1999,
            mibaoPrize:414,
            mibaoUnit:'(14天)',
            discontPrize:314,
            discontUnit:'14天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/chuxing-3.png')
          }
        ],
      },
      {
        category:'办公',
        bonusList:{
          common:[
            {
              price:88,
              condition:'满100元可用'
            }
          ],
          jd:[]
        },
        goodsInfoList:[
          {
            id:776,
            name:'三木碎纸机 MSD9711',
            originalPrize:1599,
            mibaoPrize:99,
            mibaoUnit:'/月',
            discontPrize:11,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/bangong-1.png')
          },{
            id:778,
            name:'惠普打印机',
            originalPrize:3699,
            mibaoPrize:219,
            mibaoUnit:'/月',
            discontPrize:131,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/bangong-2.png')
          },{
            id:777,
            name:'三木碎纸机 MSD9620',
            originalPrize:2799,
            mibaoPrize:149,
            mibaoUnit:'/月',
            discontPrize:61,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/bangong-3.png')
          }
        ],
      },
      {
        category:'游戏',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满88元可用'
            }
          ],
          jd:[]
        },
        goodsInfoList:[
          {
            id:1070,
            name:'Switch主机加游戏套餐',
            originalPrize:2500,
            mibaoPrize:119,
            mibaoUnit:'(30天)',
            discontPrize:69,
            discontUnit:'30天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/youxi-1.png')
          },{
            id:1343,
            name:'喵游包邮PS4主机游戏套餐',
            originalPrize:1900,
            mibaoPrize:210,
            mibaoUnit:'(30天)',
            discontPrize:160,
            discontUnit:'30天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/youxi-2.png')
          },{
            id:340,
            name:'Xbox360体感套机',
            originalPrize:1999,
            mibaoPrize:210,
            mibaoUnit:'(7天)',
            discontPrize:160,
            discontUnit:'7天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/youxi-3.png')
          }
        ],
      },
      {
        category:'智能学习',
        bonusList:{
          common:[
            {
              price:50,
              condition:'满68元可用'
            }
          ],
          jd:[]
        },
        goodsInfoList:[
          {
            id:654,
            name:'科大讯飞译呗随身翻译器',
            originalPrize:1199,
            mibaoPrize:98,
            mibaoUnit:'(7天)',
            discontPrize:48,
            discontUnit:'7天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/zhinengxuexi-1.png')
          },{
            id:835,
            name:'Kindle Oasis 电子书',
            originalPrize:2658,
            mibaoPrize:189,
            mibaoUnit:'/月',
            discontPrize:139,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/zhinengxuexi-2.png')
          },{
            id:834,
            name:'Kindle PaperWhite电子书',
            originalPrize:958,
            mibaoPrize:69,
            mibaoUnit:'/月',
            discontPrize:19,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/zhinengxuexi-3.png')
          }
        ],
      },
      {
        category:'全品类',
        bonusList:{
          common:[
            {
              price:30,
              condition:''
            }
          ],
          jd:[]
        },
        goodsInfoList:[
          {
            id:1044,
            name:'任天堂Switch游戏任选',
            originalPrize:360,
            mibaoPrize:42,
            mibaoUnit:'(14天)',
            discontPrize:12,
            discontUnit:'14天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/quanpinlei-1.png')
          },{
            id:1205,
            name:'希尔顿电动牙刷',
            originalPrize:398,
            mibaoPrize:30,
            mibaoUnit:'/月',
            discontPrize:0,
            discontUnit:'首月',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/quanpinlei-2.png')
          },{
            id:1345,
            name:'喵游包邮PS4主机游戏光碟',
            originalPrize:400,
            mibaoPrize:46,
            mibaoUnit:'(7天)',
            discontPrize:16,
            discontUnit:'7天',
            imgUrl:require('../assets/img/varyActivity/lottery20180618/goods/quanpinlei-3.png')
          }
        ],
      }
    ]
  };
export default goodsInfo618
