const recommendGoodsList =
  {
    tabsData:['全品类优惠','潮流数码','手机电脑','家电生活'],
    goodsData:[
      {
        category:'全品类优惠',
        goodsInfoList:[
          {
            id:1533,
            name:'GOOVIS G1 移动3D影院 高清 护眼 轻巧 不晕',
            originalPrize:3599,
            mibaoPrize:27,
            mibaoUnit:'7天',
            discontPrize:0,
            discontUnit:'7天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/all-goods01.png')
          },{
            id:581,
            name:'Beats pill+',
            originalPrize:1588,
            mibaoPrize:126,
            mibaoUnit:'7天',
            discontPrize:0,
            discontUnit:'7天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/all-goods02.png')
          },{
            id:1475,
            name:'JBL GO音乐金砖音响',
            originalPrize:299,
            mibaoPrize:241,
            mibaoUnit:'1个月',
            discontPrize:0,
            discontUnit:'1个月',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/all-goods03.png')
          },{
            id:1070,
            name:'喵游包邮switch主机游戏套餐',
            originalPrize:2500,
            mibaoPrize:255,
            mibaoUnit:'首付',
            discontPrize:55,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/all-goods04.png')
          }
        ]
      },
      {
        category:'潮流数码',
        goodsInfoList:[
          {
            id:534,
            name:'佳能新款微单M100 15-45套机新款潮流旅游型家用微单',
            originalPrize:3299,
            mibaoPrize:195,
            mibaoUnit:'3天',
            discontPrize:0,
            discontUnit:'3天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/chaoliushuma01.png')
          },{
            id:300,
            name:'DJI/大疆 御 Mavic PRO',
            originalPrize:7599,
            mibaoPrize:222,
            mibaoUnit:'3天',
            discontPrize:22,
            discontUnit:'3天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/chaoliushuma02.png')
          },{
            id:275,
            name:'佳能新款750D 18-55 18-135 旅游型单反相机',
            originalPrize:4500,
            mibaoPrize:262,
            mibaoUnit:'7天',
            discontPrize:62,
            discontUnit:'7天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/chaoliushuma03.png')
          },{
            id:873,
            name:'DJI大疆 御 Mavic Air 便携可折叠4K无人机 ',
            originalPrize:6499,
            mibaoPrize:560,
            mibaoUnit:'7天',
            discontPrize:360,
            discontUnit:'7天',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/chaoliushuma04.png')
          }
        ]
      },
      {
        category:'手机电脑',
        goodsInfoList:[
          {
            id:1285,
            name:'2018新款 iPad 9.7英寸',
            originalPrize:2600,
            mibaoPrize:165,
            mibaoUnit:'首付',
            discontPrize:0,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/shoujidiannao01.png')
          },{
            id:2880,
            name:'vivo X21',
            originalPrize:2898,
            mibaoPrize:397,
            mibaoUnit:'首付',
            discontPrize:197,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/shoujidiannao02.png')
          },{
            id:628,
            name:'Apple Watch 二代S2',
            originalPrize:2588,
            mibaoPrize:398,
            mibaoUnit:'1个月',
            discontPrize:198,
            discontUnit:'1个月',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/shoujidiannao03.png')
          },{
            id:1231,
            name:'iphone7plus',
            originalPrize:5540,
            mibaoPrize:259,
            mibaoUnit:'首付',
            discontPrize:59,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/shoujidiannao04.png')
          }
        ]
      },
      {
        category:'家电生活',
        goodsInfoList:[
          {
            id:1205,
            name:'希尔顿 电动牙刷（X6）成人充电式声波牙刷 进口细丝软毛',
            originalPrize:398,
            mibaoPrize:30,
            mibaoUnit:'首付',
            discontPrize:0,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/jiadianshenghuo01.png')
          },{
            id:947,
            name:'海尔紫外线杀菌除螨仪 ZB403F',
            originalPrize:699,
            mibaoPrize:150,
            mibaoUnit:'1个月',
            discontPrize:0,
            discontUnit:'1个月',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/jiadianshenghuo02.png')
          },{
            id:357,
            name:'范罗士DX95空气净化器',
            originalPrize:2998,
            mibaoPrize:210,
            mibaoUnit:'首付',
            discontPrize:10,
            discontUnit:'首付',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/jiadianshenghuo03.png')
          },{
            id:1409,
            name:'SODASODA气泡机',
            originalPrize:980,
            mibaoPrize:212,
            mibaoUnit:'6个月',
            discontPrize:12,
            discontUnit:'6个月',
            imgUrl:require('../../assets/img/varyActivity/scoresQuiz/a20180625/recommend/jiadianshenghuo04.png')
          }
        ]
      },
    ]
  };
export default recommendGoodsList
